[package]
name = "bevy_quinnet"
version = "0.4.0-dev"
description = "Bevy plugin for Client/Server multiplayer games using QUIC"
repository = "https://github.com/Henauxg/bevy_quinnet"
documentation = "https://docs.rs/bevy_quinnet"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["gamedev", "networking", "quic", "bevy", "plugin"]
categories = ["game-development", "network-programming"]
readme = "README.md"
exclude = ["assets/"]

[dependencies]
bevy = { version = "0.9", git = "https://github.com/bevyengine/bevy", rev="1ffeff19f9e01f68cd24d64d2bf281926da90d58", default-features = false }
rustls = { version = "0.20.6", default-features = false, features = ["quic", "dangerous_configuration"] }
rustls-pemfile = "1.0.1"
ring = "0.16.20"
tokio = { version = "1.21.2", features = ["sync", "rt-multi-thread", "macros"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
rcgen = "0.10.0"
quinn = "0.9.1"
quinn-proto = "0.9.1"
futures-util = "0.3.24"
futures = "0.3.24"
bincode = "1.3.3"
serde = "1.0.145"
bytes = "1.2.1"
base64 = "0.13.1"
thiserror = "1.0.37"

[dev-dependencies]
bevy = { version = "0.9",git = "https://github.com/bevyengine/bevy", rev="1ffeff19f9e01f68cd24d64d2bf281926da90d58",  default-features = false, features = ["bevy_asset", "bevy_audio", "vorbis", "bevy_winit", "bevy_render"] }
rand = "0.8.5"

# [[example]]
# name = "breakout"
# path = "examples/breakout/breakout.rs"

[[example]]
name = "chat-server"
path = "examples/chat/server.rs"

[[example]]
name = "chat-client"
path = "examples/chat/client.rs"
